version: '3.8'

services:
  # VictoriaMetrics Cluster components for COD1 (Data Center 1)
  vminsert-cod1:
    image: victoriametrics/vminsert:v1.95.1-cluster
    container_name: vminsert-cod1
    restart: always
    ports:
      - "8480:8480"
    command:
      - '-storageNode=cod1_vmstorage:8400'
      - '-storageNode=cod2_vmstorage:8400'
      - '-replicationFactor=2'
      - '-httpListenAddr=:8480'
    networks:
      - vmnet
    depends_on:
      - cod1_vmstorage
      - cod2_vmstorage

  # VictoriaMetrics Cluster components for COD2 (Data Center 2)
  vminsert-cod2:
    image: victoriametrics/vminsert:v1.95.1-cluster
    container_name: vminsert-cod2
    restart: always
    ports:
      - "8481:8480"
    command:
      - '-storageNode=cod1_vmstorage:8400'
      - '-storageNode=cod2_vmstorage:8400'
      - '-replicationFactor=2'
      - '-httpListenAddr=:8480'
    networks:
      - vmnet
    depends_on:
      - cod1_vmstorage
      - cod2_vmstorage

  vmselect-cod1:
    image: victoriametrics/vmselect:v1.95.1-cluster
    container_name: vmselect-cod1
    restart: always
    ports:
      - "8481:8481"
    command:
      - '-storageNode=cod1_vmstorage:8401'
      - '-storageNode=cod2_vmstorage:8401'
      - '-httpListenAddr=:8481'
      - '-cacheDataPath=/tmp/vmselect-cod1'
    volumes:
      - vmselect_cod1_cache:/tmp/vmselect-cod1
    networks:
      - vmnet
    depends_on:
      - cod1_vmstorage
      - cod2_vmstorage

  vmselect-cod2:
    image: victoriametrics/vmselect:v1.95.1-cluster
    container_name: vmselect-cod2
    restart: always
    ports:
      - "8482:8481"
    command:
      - '-storageNode=cod1_vmstorage:8401'
      - '-storageNode=cod2_vmstorage:8401'
      - '-httpListenAddr=:8481'
      - '-cacheDataPath=/tmp/vmselect-cod2'
    volumes:
      - vmselect_cod2_cache:/tmp/vmselect-cod2
    networks:
      - vmnet
    depends_on:
      - cod1_vmstorage
      - cod2_vmstorage

  cod1_vmstorage:
    image: victoriametrics/vmstorage:v1.95.1-cluster
    container_name: cod1_vmstorage
    restart: always
    ports:
      - "8400:8400"
      - "8401:8401"
      - "8482:8482"
    command:
      - '-storageDataPath=/storage'
      - '-httpListenAddr=:8482'
      - '-vminsertAddr=:8400'
      - '-vmselectAddr=:8401'
    volumes:
      - vmstorage_cod1_data:/storage
    networks:
      - vmnet

  cod2_vmstorage:
    image: victoriametrics/vmstorage:v1.95.1-cluster
    container_name: cod2_vmstorage
    restart: always
    ports:
      - "9400:8400"
      - "9401:8401"
      - "9482:8482"
    command:
      - '-storageDataPath=/storage'
      - '-httpListenAddr=:8482'
      - '-vminsertAddr=:8400'
      - '-vmselectAddr=:8401'
    volumes:
      - vmstorage_cod2_data:/storage
    networks:
      - vmnet

networks:
  vmnet:
    driver: bridge

volumes:
  vmselect_cod1_cache:
  vmselect_cod2_cache:
  vmstorage_cod1_data:
  vmstorage_cod2_data: